const els = {
  keyboard: document.querySelector('#keyboard'), start: document.querySelector('#startButton'), reset: document.querySelector('#resetButton'), speed: document.querySelector('#speedSelect'), source: document.querySelector('#sourceSelect'), samples: document.querySelector('#sampleSelect'), custom: document.querySelector('#customMessage'), targetLabel: document.querySelector('#targetLabel'), targetText: document.querySelector('#targetText'), intentLength: document.querySelector('#intentLength'), intentSource: document.querySelector('#intentSource'), evidenceNote: document.querySelector('#evidenceNote'), connection: document.querySelector('#connectionState'), decoded: document.querySelector('#decodedText'), progress: document.querySelector('#progressText'), bar: document.querySelector('#progressBar'), phase: document.querySelector('#phaseBadge'), stimulus: document.querySelector('#currentStimulus'), evidence: document.querySelector('#evidenceScore'), flashes: document.querySelector('#flashCount'), scan: document.querySelector('#scanCopy'), signal: document.querySelector('#signalValue'), signalLabel: document.querySelector('#signalLabel'), marker: document.querySelector('#p300Marker'), state: document.querySelector('#decodeState'), confidence: document.querySelector('#confidenceBadge'), lastChar: document.querySelector('#lastChar'), lastLabel: document.querySelector('#lastLabel'), lastDetail: document.querySelector('#lastDetail'), events: document.querySelector('#eventList'), context: document.querySelector('#contextText'), explanation: document.querySelector('#contextExplanation'), chips: document.querySelector('#predictionChips'), prior: document.querySelector('#priorConfidence'), priority: document.querySelector('#priorityTarget'), priorityDesc: document.querySelector('#priorityDescription'), saving: document.querySelector('#flashSaving'), ragOptions: document.querySelector('#speedDialOptions'), ragStatus: document.querySelector('#speedDialStatus'), bars: ['#barOne', '#barTwo', '#barThree', '#barFour'].map(s => document.querySelector(s)), canvas: document.querySelector('#waveCanvas'),
};
const state = { result: null, selection: 0, trace: 0, timer: null, running: false, events: [], evidence: 0 };
const displayKey = key => key === 'Sp' ? 'SPACE' : key === 'Prd' ? '.' : key;
const displayChar = char => char === ' ' ? '␠' : char;
const escapeHtml = value => value.replace(/[&<>]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[char]);
const cell = key => document.querySelector(`.key[data-key="${CSS.escape(key)}"]`);
function setPhase(text, active = false) { els.phase.innerHTML = `<span></span> ${text}`; els.phase.classList.toggle('active', active); }
function addEvent(message, emphasis = '') { const now = new Date().toLocaleTimeString([], { minute: '2-digit', second: '2-digit' }); state.events.unshift({ now, message, emphasis }); state.events = state.events.slice(0, 5); els.events.innerHTML = state.events.map(e => `<div class="event"><time>${e.now}</time>${e.emphasis ? `<strong>${e.emphasis}</strong> ` : ''}${e.message}</div>`).join(''); }
function clearGrid() { document.querySelectorAll('.key').forEach(node => node.classList.remove('priority', 'target', 'flashing', 'eeg-detected')); }
function buildKeyboard(keys) { els.keyboard.innerHTML = ''; keys.forEach(key => { const button = document.createElement('button'); button.className = `key${key.length > 1 ? ' special' : ''}`; button.dataset.key = key; button.textContent = displayKey(key); button.tabIndex = -1; els.keyboard.appendChild(button); }); }
function currentTarget() { return els.source.value === 'replay' ? els.samples.selectedOptions[0]?.dataset.target || '' : els.custom.value.toUpperCase(); }
function updateTargetPreview() { const target = currentTarget(), source = els.source.value === 'replay' ? 'held-out Study D replay' : 'custom simulated EEG'; els.targetText.textContent = target || 'Choose a sample'; els.intentLength.textContent = `${target.length} characters`; els.intentSource.textContent = source; }
function setSourceMode() { const replay = els.source.value === 'replay'; els.samples.hidden = !replay; els.custom.hidden = replay; els.targetLabel.textContent = replay ? 'STUDY D SAMPLE' : 'CUSTOM SENTENCE'; reset(); updateTargetPreview(); els.evidenceNote.textContent = replay ? 'Choose a held-out session to replay its recorded EEG classifier evidence.' : 'Custom text uses simulated target-conditioned EEG likelihoods; no recorded EEG is claimed.'; els.signalLabel.textContent = replay ? 'EEG / P300 RESPONSE' : 'SIMULATED EEG / DECODER POSTERIOR'; }
function renderPrior(selection) {
  const { top, rag } = selection.prior; document.querySelectorAll('.key').forEach(node => node.classList.remove('priority')); top.forEach(item => cell(item.key)?.classList.add('priority'));
  els.chips.innerHTML = top.map((item, i) => `<span class="chip ${i === 0 ? 'top' : ''}">${displayKey(item.key)} <b>${Math.round(item.probability * 100)}%</b></span>`).join('');
  els.prior.textContent = `top prior ${Math.round((top[0]?.probability || 0) * 100)}%`; els.priority.textContent = top.map(item => displayKey(item.key)).join(' · ');
  els.priorityDesc.textContent = rag.enabled ? `Global retrieval blended at ${Math.round(rag.global_weight * 100)}% weight.` : `Global retrieval ${rag.reason.replaceAll('_', ' ')}; base LLM prior retained.`;
  els.ragOptions.innerHTML = rag.matches.length ? rag.matches.map(match => `<span class="chip">${escapeHtml(match)}</span>`).join('') : '<span class="chip">No compatible phrase retrieved</span>';
  els.ragStatus.textContent = rag.enabled ? `RAG active · confidence ${Math.round(rag.confidence * 100)}%` : `RAG ${rag.reason.replaceAll('_', ' ')}`;
  els.bars.forEach((bar, i) => { bar.style.height = `${Math.max(5, Math.round((top[i]?.probability || 0) * 100))}px`; });
}
function render() { const result = state.result, decoded = result ? result.selections.slice(0, state.selection).map(item => item.predicted_character).join('') : '', target = result?.target || currentTarget(); els.decoded.innerHTML = `${escapeHtml(decoded)}<span class="cursor"></span>`; els.progress.textContent = `${state.selection} / ${result?.selections.length || target.length}`; els.bar.style.width = `${result?.selections.length ? (state.selection / result.selections.length) * 100 : 0}%`; els.context.textContent = decoded || 'No decoded context yet'; els.explanation.textContent = decoded ? 'The next prior is computed from decoder output, not the intended target.' : 'The first character uses the backend predictor’s empty-context prior.'; els.saving.textContent = result ? `${result.summary.mean_sequences_per_character} / 15` : '—'; }
function drawWave() { const canvas = els.canvas, ctx = canvas.getContext('2d'), dpr = devicePixelRatio || 1, width = canvas.clientWidth, height = canvas.clientHeight; canvas.width = width * dpr; canvas.height = height * dpr; ctx.scale(dpr, dpr); ctx.clearRect(0, 0, width, height); ctx.strokeStyle = '#e5ece5'; ctx.lineWidth = 1; for (let y = 20; y < height; y += 27) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(width, y); ctx.stroke(); } ctx.beginPath(); for (let x = 0; x < width; x += 1) { const baseline = Math.sin(x * .085) * 3 + Math.sin(x * .028) * 2, peak = Math.exp(-Math.pow((x - width * .34) / 34, 2)) * state.evidence * 35, y = height * .55 + baseline - peak; x ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.strokeStyle = '#278359'; ctx.lineWidth = 1.7; ctx.stroke(); }
function showTrace() { if (!state.running || !state.result) return; const selection = state.result.selections[state.selection], trace = selection.trace[state.trace]; if (!trace) return confirmSelection(); state.evidence = trace.target_evidence; drawWave(); els.marker.classList.toggle('show', trace.target_evidence > .1); els.signal.textContent = trace.target_evidence.toFixed(2); els.evidence.textContent = trace.target_evidence.toFixed(2); els.stimulus.textContent = `SEQUENCE ${trace.sequence} / 15`; els.flashes.textContent = `${trace.sequence}`; els.scan.textContent = `Decoder top key: ${displayKey(trace.predicted_key)} · posterior ${Math.round(trace.decoder_confidence * 100)}%`; state.trace += 1; state.timer = setTimeout(showTrace, 580 / Number(els.speed.value)); }
function beginSelection() { if (!state.running || !state.result) return; if (state.selection >= state.result.selections.length) return finish(); const selection = state.result.selections[state.selection]; state.trace = 0; clearGrid(); cell(selection.target_key)?.classList.add('target'); renderPrior(selection); render(); els.state.textContent = 'Accumulating backend evidence'; els.confidence.textContent = '—'; addEvent(`Character ${selection.index + 1}: prior prepared from decoded context.`, 'Prior ready'); showTrace(); }
function confirmSelection() { const selection = state.result.selections[state.selection]; clearTimeout(state.timer); cell(selection.predicted_key)?.classList.add('eeg-detected'); const predicted = displayChar(selection.predicted_character); els.lastChar.textContent = predicted; els.lastLabel.textContent = `${predicted} ${selection.correct ? 'matches recorded target' : 'does not match recorded target'}`; els.lastDetail.textContent = `${selection.sequences} sequence(s) · decoder confidence ${Math.round(selection.confidence * 100)}%`; els.confidence.textContent = `${Math.round(selection.confidence * 100)}% confidence`; els.state.textContent = 'Decoder selection confirmed'; addEvent(`Decoder selected ${displayKey(selection.predicted_key)} after ${selection.sequences} sequence(s).`, selection.correct ? 'Confirmed' : 'Mismatch'); state.selection += 1; render(); state.timer = setTimeout(beginSelection, 620 / Number(els.speed.value)); }
function finish() { state.running = false; clearTimeout(state.timer); setPhase('Backend run complete'); els.start.innerHTML = '✓ Run complete'; els.start.classList.add('running'); els.scan.textContent = `Accuracy ${state.result.summary.accuracy}% · ${state.result.summary.sequences} accumulated sequences`; els.state.textContent = 'Backend result reproduced'; addEvent('Backend run reproduced in the interface.', 'Complete'); }
function reset() { state.running = false; state.result = null; state.selection = 0; state.trace = 0; state.evidence = 0; state.events = []; clearTimeout(state.timer); clearGrid(); els.events.innerHTML = ''; els.chips.innerHTML = ''; els.ragOptions.innerHTML = ''; els.ragStatus.textContent = 'Backend RAG diagnostics appear here'; els.stimulus.textContent = '—'; els.evidence.textContent = '0.00'; els.flashes.textContent = '0'; els.signal.textContent = '0.0'; els.marker.classList.remove('show'); els.scan.textContent = 'Load a backend run to inspect its evidence trace'; els.lastChar.textContent = '—'; els.lastLabel.textContent = 'No selection yet'; els.lastDetail.textContent = 'Confidence will appear here.'; els.confidence.textContent = '—'; els.state.textContent = 'Waiting for backend evidence'; els.priority.textContent = '—'; els.priorityDesc.textContent = 'Waiting to prioritize'; els.prior.textContent = '—'; els.bars.forEach(bar => { bar.style.height = '0px'; }); els.start.innerHTML = '<span class="play-icon">▶</span> Load backend run'; els.start.classList.remove('running'); setPhase('Awaiting backend run'); render(); drawWave(); }
async function loadRun() {
  if (state.running) { state.running = false; clearTimeout(state.timer); els.start.innerHTML = '<span class="play-icon">▶</span> Resume run'; els.start.classList.remove('running'); setPhase('Playback paused'); return; }
  if (state.result && state.selection < state.result.selections.length) { state.running = true; els.start.innerHTML = '<span class="play-icon">Ⅱ</span> Pause playback'; els.start.classList.add('running'); setPhase('Evidence playback live', true); return beginSelection(); }
  const replay = els.source.value === 'replay', payload = replay ? { session_id: els.samples.value } : { message: els.custom.value }; els.start.disabled = true; els.start.textContent = 'Running backend…'; setPhase('Backend is decoding', true);
  try { const response = await fetch(replay ? '/api/replay' : '/api/simulate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }), result = await response.json(); if (!response.ok) throw new Error(result.error || 'Backend request failed'); reset(); state.result = result; els.targetText.textContent = result.target; els.intentLength.textContent = `${result.summary.characters} characters`; els.intentSource.textContent = result.source === 'study_d_replay' ? 'recorded Study D data' : 'custom simulation'; els.evidenceNote.textContent = result.evidence_notice; els.signalLabel.textContent = result.source === 'study_d_replay' ? 'RECORDED EEG / SWLDA POSTERIOR' : 'SIMULATED EEG / DECODER POSTERIOR'; state.running = true; els.start.innerHTML = '<span class="play-icon">Ⅱ</span> Pause playback'; els.start.classList.add('running'); setPhase('Evidence playback live', true); addEvent(result.evidence_notice, 'Backend ready'); beginSelection(); }
  catch (error) { setPhase('Backend error'); els.scan.textContent = error.message; addEvent(error.message, 'Error'); }
  finally { els.start.disabled = false; if (!state.running) els.start.innerHTML = '<span class="play-icon">▶</span> Load backend run'; }
}
async function initialise() { try { const [healthResponse, samplesResponse] = await Promise.all([fetch('/api/health'), fetch('/api/samples')]), health = await healthResponse.json(), samples = await samplesResponse.json(); if (!healthResponse.ok || !samplesResponse.ok) throw new Error(health.error || samples.error || 'Backend unavailable'); buildKeyboard(health.grid.keys); els.samples.innerHTML = samples.samples.map(sample => `<option value="${sample.id}" data-target="${escapeHtml(sample.target)}">${sample.id} · ${sample.target}</option>`).join(''); els.connection.innerHTML = '<i></i> Backend connected'; els.connection.title = health.custom_text_notice; updateTargetPreview(); reset(); } catch (error) { els.connection.textContent = 'Backend unavailable'; els.connection.classList.add('offline'); els.start.disabled = true; els.scan.textContent = 'Start prototype/server.py to connect the real backend.'; } }
els.start.addEventListener('click', loadRun); els.reset.addEventListener('click', reset); els.source.addEventListener('change', setSourceMode); els.samples.addEventListener('change', () => { reset(); updateTargetPreview(); }); els.custom.addEventListener('input', () => { reset(); updateTargetPreview(); }); window.addEventListener('resize', drawWave); initialise();
