const targetMessage = 'I would like water, please.';
// Exact Study D 9 x 8 map, read from data/processed/grid_layout.json.
const grid = [
 ['A','B','C','D','E','F','G','H'], ['I','J','K','L','M','N','O','P'],
 ['Q','R','S','T','U','V','W','X'], ['Y','Z','Sp','1','2','3','4','5'],
 ['6','7','8','9','0','Prd','Ret','Bs'], ['?',',',';','\\','/','+','-','Alt'],
 ['Ctrl','=','Del','Home','UpAw','End','PgUp','Shft'], ["Save","'",'F2','LfAw','DnAw','RtAw','PgDn','Pause'],
 ['Caps','F5','Tab','EC','Esc','email','!','Sleep']
];
const els={keyboard:document.querySelector('#keyboard'),start:document.querySelector('#startButton'),reset:document.querySelector('#resetButton'),speed:document.querySelector('#speedSelect'),decoded:document.querySelector('#decodedText'),progress:document.querySelector('#progressText'),bar:document.querySelector('#progressBar'),phase:document.querySelector('#phaseBadge'),stimulus:document.querySelector('#currentStimulus'),evidence:document.querySelector('#evidenceScore'),flashes:document.querySelector('#flashCount'),scan:document.querySelector('#scanCopy'),signal:document.querySelector('#signalValue'),marker:document.querySelector('#p300Marker'),state:document.querySelector('#decodeState'),confidence:document.querySelector('#confidenceBadge'),lastChar:document.querySelector('#lastChar'),lastLabel:document.querySelector('#lastLabel'),lastDetail:document.querySelector('#lastDetail'),events:document.querySelector('#eventList'),context:document.querySelector('#contextText'),explanation:document.querySelector('#contextExplanation'),chips:document.querySelector('#predictionChips'),prior:document.querySelector('#priorConfidence'),priority:document.querySelector('#priorityTarget'),priorityDesc:document.querySelector('#priorityDescription'),saving:document.querySelector('#flashSaving'),speedOptions:document.querySelector('#speedDialOptions'),speedStatus:document.querySelector('#speedDialStatus'),bars:['#barOne','#barTwo','#barThree','#barFour'].map(s=>document.querySelector(s))};
let state={running:false,index:0,flashes:0,step:0,timer:null,waveTimer:null,events:[],lastPrior:[],p300Active:false,mode:'speed',speedWords:[],priorityKeys:[],probeIndex:0};
const special=new Set(grid.flat().filter(k=>k.length>1));
const label=k=>k==='Sp'?'SPACE':k;
const dataKeyForChar=c=>c===' '?'Sp':c.toUpperCase();
const targetPosition=c=>{const key=dataKeyForChar(c);for(let r=0;r<9;r++){const col=grid[r].indexOf(key);if(col>=0)return {key,row:r,col}}return null};
function buildKeyboard(){grid.flat().forEach((key,i)=>{const b=document.createElement('button');b.className='key'+(special.has(key)?' special':'');b.dataset.key=key;b.dataset.row=Math.floor(i/8)+1;b.dataset.col=i%8+1;b.textContent=label(key);b.setAttribute('tabindex','-1');els.keyboard.appendChild(b)})}
function cell(key){return document.querySelector(`.key[data-key="${CSS.escape(key)}"]`)}
function prediction(next){const map={'I':[' ','M','W','T'],'W':['A','E','I','O'],'A':['T','N','R','S'],'T':['H','O','E','I'],'P':['L','R','E','A'],',':[' ','P','T','A'],' ':['T','I','W','P']};const list=map[next.toUpperCase()]||[next.toUpperCase(),'E','A','R'];return [...new Set(list)].slice(0,4)}
function updatePrior(next){const values=prediction(next);state.lastPrior=values;document.querySelectorAll('.key').forEach(k=>k.classList.remove('priority'));values.forEach(v=>cell(dataKeyForChar(v))?.classList.add('priority'));els.chips.innerHTML=values.map((v,i)=>`<span class="chip ${i===0?'top':''}">${v===' '?'SPACE':v} <b>${47-i*10}%</b></span>`).join('');els.prior.textContent='top prior 47%';els.priority.textContent=values.map(v=>v===' '?'SPACE':v).join(' · ');els.priorityDesc.textContent='These cells flash before the full 9×8 row/column fallback; EEG evidence decides every step.';els.bars.forEach((b,i)=>b.style.height=`${24-i*5}px`)}
function targetWord(){const remaining=targetMessage.slice(state.index).replace(/^\s+/,'');return remaining.match(/^[A-Za-z]+/)?.[0]||''}
function speedWords(){const word=targetWord();const alternatives={i:['I','YES','HELLO','HELP'],would:['will','would','want','need'],like:['like','love','need','want'],water:['water','help','food','rest'],please:['thanks','please','yes','help']};const fallback=['yes','help','thanks','please'];return [...new Set(alternatives[word.toLowerCase()]||fallback)].slice(0,4)}
function renderSpeedDial(){els.speedOptions.innerHTML=state.speedWords.map(word=>`<button class="speed-option" data-word="${word}">${word}</button>`).join('');els.speedStatus.textContent='Word candidates flash before character and full-grid fallback'}
function prepareSelection(){state.mode='speed';state.step=0;state.probeIndex=0;state.speedWords=speedWords();state.priorityKeys=prediction(targetMessage[state.index]);markTarget();updatePrior(targetMessage[state.index]);renderSpeedDial()}
function setP300(active){state.p300Active=active;els.marker.classList.toggle('show',active);els.signal.textContent=active?`+${(5.3+Math.random()*2).toFixed(1)}`:`+${(0.6+Math.random()*1.6).toFixed(1)}`;els.evidence.textContent=active?(.72+Math.random()*.18).toFixed(2):(.08+Math.random()*.17).toFixed(2)}
function markTarget(){document.querySelectorAll('.key').forEach(k=>k.classList.remove('target'));const pos=targetPosition(targetMessage[state.index]);if(pos)cell(pos.key)?.classList.add('target')}
function render(){const text=targetMessage.slice(0,state.index);els.decoded.innerHTML=`${escapeHtml(text)}<span class="cursor"></span>`;els.progress.textContent=`${state.index} / ${targetMessage.length}`;els.bar.style.width=`${state.index/targetMessage.length*100}%`;els.flashes.textContent=state.flashes;els.context.textContent=text||'No decoded context yet';els.explanation.textContent=text?'Prior is conditioned on decoded text and the AAC phrase bank.':'A uniform prior will be used until text is selected.';els.saving.textContent=state.index?`${Math.round(state.index*2.4)} flashes saved`:'—'}
function escapeHtml(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function addEvent(message,emphasis=''){const now=new Date().toLocaleTimeString([],{minute:'2-digit',second:'2-digit'});state.events.unshift({now,message,emphasis});state.events=state.events.slice(0,5);els.events.innerHTML=state.events.map(e=>`<div class="event"><time>${e.now}</time>${e.emphasis?`<strong>${e.emphasis}</strong> `:''}${e.message}</div>`).join('')}
function setPhase(text,active=false){els.phase.innerHTML=`<span></span> ${text}`;els.phase.classList.toggle('active',active)}
function clearFlash(){document.querySelectorAll('.key').forEach(k=>k.classList.remove('flashing','eeg-detected'))}
function selectCharacter(){const char=targetMessage[state.index];const pos=targetPosition(char);clearFlash();cell(pos.key)?.classList.add('eeg-detected');const confidence=(.88+Math.random()*.09).toFixed(2);state.index++;state.step=0;els.lastChar.textContent=char===' '?'␠':char;els.lastLabel.textContent=`“${char===' '?'space':char}” confirmed`;els.lastDetail.textContent=`Row ${pos.row+1} + column ${pos.col+1} P300 evidence · ${confidence}`;els.confidence.textContent=`${confidence} confidence`;els.state.textContent='EEG evidence confirmed the selection';els.evidence.textContent=confidence;addEvent(`EEG evidence confirmed “${char===' '?'space':char}”.`, 'Selection confirmed');render();if(state.index>=targetMessage.length){finish();return}prepareSelection();state.timer=setTimeout(flashTick,220/Number(els.speed.value))}
function selectWord(word){document.querySelectorAll('.speed-option').forEach(b=>b.classList.remove('flashing'));document.querySelector(`.speed-option[data-word="${word}"]`)?.classList.add('detected');const prefix=targetMessage.slice(state.index).startsWith(' ')?' ':'';state.index+=word.length+prefix.length;const confidence=(.89+Math.random()*.08).toFixed(2);els.lastChar.textContent='↳';els.lastLabel.textContent=`“${word}” confirmed`;els.lastDetail.textContent=`LLM speed dial + EEG P300 evidence · ${confidence}`;els.confidence.textContent=`${confidence} confidence`;els.state.textContent='EEG confirmed a predicted word shortcut';addEvent(`Speed-dial word “${word}” produced a P300 response.`, 'Word confirmed');render();if(state.index>=targetMessage.length){finish();return}prepareSelection();state.timer=setTimeout(flashTick,220/Number(els.speed.value))}
function flashTick(){if(!state.running)return;const speed=Number(els.speed.value);const pos=targetPosition(targetMessage[state.index]);clearFlash();document.querySelectorAll('.speed-option').forEach(b=>b.classList.remove('flashing'));
 if(state.mode==='speed'){const word=state.speedWords[state.probeIndex];const hit=word===targetWord();document.querySelector(`.speed-option[data-word="${word}"]`)?.classList.add('flashing');state.flashes++;els.stimulus.textContent=`WORD · ${word}`;els.scan.textContent=hit?'Predicted word matches user intent — P300 response detected':'No P300 response — trying next word prediction';setP300(hit);if(hit){addEvent(`Speed dial “${word}” matches the intended next word.`, 'P300 spike');return setTimeout(()=>state.running&&selectWord(word),430/speed)}state.probeIndex++;if(state.probeIndex>=state.speedWords.length){state.mode='priority';state.probeIndex=0;els.speedStatus.textContent='No word response: probing next-character predictions'}return state.timer=setTimeout(flashTick,430/speed)}
 if(state.mode==='priority'){const raw=state.priorityKeys[state.probeIndex];const key=dataKeyForChar(raw);const hit=key===pos.key;cell(key)?.classList.add('flashing');state.flashes++;els.stimulus.textContent=`PRIORITY · ${label(key)}`;els.scan.textContent=hit?'LLM-prioritized character evoked a P300 response':'No P300 response — trying next predicted character';setP300(hit);if(hit){addEvent(`Priority character “${label(key)}” matches target evidence.`, 'P300 spike');return setTimeout(()=>state.running&&selectCharacter(),430/speed)}state.probeIndex++;if(state.probeIndex>=state.priorityKeys.length){state.mode='grid';state.step=0;els.speedStatus.textContent='No priority response: scanning remaining 9×8 grid'}return state.timer=setTimeout(flashTick,430/speed)}
 const isRow=state.step<9,groupIndex=isRow?state.step:state.step-9,group=isRow?grid[groupIndex]:grid.map(row=>row[groupIndex]),hit=isRow?pos.row===groupIndex:pos.col===groupIndex;group.forEach(k=>cell(k)?.classList.add('flashing'));state.flashes++;els.stimulus.textContent=`${isRow?'ROW':'COLUMN'} ${groupIndex+1} / ${isRow?'9':'8'}`;els.scan.textContent=hit?`Target belongs to this ${isRow?'row':'column'} — P300 response detected`:`${isRow?'Row':'Column'} flash ${groupIndex+1}: no target response`;setP300(hit);if(hit)addEvent(`${isRow?'Row':'Column'} ${groupIndex+1} contains intended “${label(pos.key)}”.`, 'P300 spike');state.step++;if(state.step===17)return setTimeout(()=>state.running&&selectCharacter(),430/speed);state.timer=setTimeout(flashTick,430/speed)}
function start(){if(state.running){pause();return}if(state.index>=targetMessage.length)reset();state.running=true;els.start.innerHTML='<span class="play-icon">Ⅱ</span> Pause simulation';els.start.classList.add('running');setPhase('Adaptive scan live',true);els.state.textContent='Probing LLM word and character predictions before full-grid fallback';addEvent('Adaptive P300 scan started: speed dial → priority characters → 9×8 grid.', 'Session live');prepareSelection();flashTick()}
function pause(){state.running=false;clearTimeout(state.timer);els.start.innerHTML='<span class="play-icon">▶</span> Resume simulation';els.start.classList.remove('running');setPhase('Simulation paused');els.scan.textContent='Paused — evidence preserved';addEvent('Selection stream paused.')}
function finish(){state.running=false;clearTimeout(state.timer);els.start.innerHTML='✓ Message complete';els.start.classList.add('running');setPhase('Message reproduced');els.scan.textContent='Target message fully communicated';els.state.textContent='AAC message complete';addEvent('The intended message has been reproduced.','Complete')}
function reset(){state={...state,running:false,index:0,flashes:0,step:0,events:[],lastPrior:[],p300Active:false,mode:'speed',speedWords:[],priorityKeys:[],probeIndex:0};clearTimeout(state.timer);clearFlash();document.querySelectorAll('.key').forEach(k=>k.classList.remove('priority','target'));els.speedOptions.innerHTML='';els.speedStatus.textContent='Predicted words are probed before the full grid';els.start.innerHTML='<span class="play-icon">▶</span> Start simulation';els.start.classList.remove('running');setPhase('Awaiting start');els.stimulus.textContent='—';els.evidence.textContent='0.00';els.scan.textContent='Ready: speed dial will be probed first';els.marker.classList.remove('show');els.lastChar.textContent='—';els.lastLabel.textContent='No selection yet';els.lastDetail.textContent='Confidence will appear here.';els.confidence.textContent='—';els.state.textContent='Waiting for EEG evidence';els.events.innerHTML='';els.chips.innerHTML='';els.priority.textContent='—';els.priorityDesc.textContent='Waiting to prioritize';els.prior.textContent='—';render()}
function drawWave(t){const c=document.querySelector('#waveCanvas'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e5ece5';ctx.lineWidth=1;for(let y=20;y<h;y+=27){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.beginPath();for(let x=0;x<w;x++){const base=Math.sin(x*.085+t*.004)*4+Math.sin(x*.028+t*.008)*3;const p300=state.p300Active?Math.exp(-Math.pow((x-w*.34)/34,2))*32:0;const y=h*.55+base-p300;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle='#278359';ctx.lineWidth=1.7;ctx.stroke()}
function startWave(){const loop=t=>{drawWave(t);state.waveTimer=requestAnimationFrame(loop)};state.waveTimer=requestAnimationFrame(loop)}
buildKeyboard();render();drawWave(0);startWave();els.start.addEventListener('click',start);els.reset.addEventListener('click',reset);
